---
app:
  name: "Snk Server"
  verbose: true
  enable_log: false
  data:
    storage: ./shared/data/storage
    cache: ./shared/data/cache
    export: ./shared/export
  web:
    static:
      prefix_path: ./shared/dist/web
    title: SNK
    javascript_path: /javascripts
    image_path: /images
    css_path: /styles
  limits:
    page_size: 20
    max_page_size: 200
    min_page_size: 10
    min_order: 0
    max_order: 10000
    max_name_length: 100
    max_content_length: 10000
    max_article_cate_count: 6
    max_comment_length: 5000
  use_proxy: false
  proxy_uri: http://127.0.0.1:8881
  port: 8020
  static_port: 8021

websocket:
  port: 8025
  auth:
    username: snk
    password: snk
  enable_log: true

database:
  dialect: sqlite3
  database: "snk-server"
  user: root
  password: root
  charset: utf8
  host: 127.0.0.1
  port: 3306
  max_idle_conns: 5

server:
  env: dev
  session_id: goesid
  port: 8080
  engine: iris
  settings:
    iris:
      disable_startup_log: true
      disable_interrupt_handler: false
      disable_path_correction: true
      enable_path_escape: true
      fire_method_not_allowed: false
      disable_body_consumption_on_unmarshal: false
      disable_auto_fire_status_code: false
      time_format: Mon, 02 Jan 2006 15:04:05 GMT
      charset: UTF-8
    gin: null